#Server configuration
server.servlet.context-path=/stationSki
server.port=8087
### DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/ski\db?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# Configuration de test H2 en mémoire
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate pour les tests
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Désactiver la validation
spring.main.allow-bean-definition-overriding=true

# Désactiver le chargement des données
spring.sql.init.mode=never

# Logging
logging.level.com.example.gestionstationskii=DEBUG