# ---------------------------
# Server configuration
# ---------------------------
server.servlet.context-path=/stationSki
server.port=8080  # Keep 8080 inside container; host maps it to 8087 in docker-compose

# ---------------------------
# Datasource (MySQL)
# ---------------------------
spring.datasource.url=jdbc:mysql://mysql:3306/station_ski_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=user
spring.datasource.password=userpassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ---------------------------
# JPA / Hibernate
# ---------------------------
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect



# ---------------------------
# Logging
# ---------------------------
logging.level.org.springframework=INFO
logging.level.com.example=DEBUG
