server:
  port: 8083
  address: 0.0.0.0

spring:
  application:
    name: my-spring-boot-app

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
