scrape_configs:
  - job_name: 'springboot-app-lb'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['abccb4a4c2f354dd5817c596ecf5b6b1-1125471686.us-east-1.elb.amazonaws.com:8083']
